export const FETCH_TEACHERDETAIL_REQUEST = 'FETCH_TEACHERDETAIL_REQUEST'
export const FETCH_TEACHERDETAIL_SUCCESS = 'FETCH_TEACHERDETAIL_SUCCESS'
export const FETCH_TEACHERDETAIL_FALIURE = 'FETCH_TEACHERDETAIL_FALIURE'
