export const FETCH_STUDENTDETAIL_REQUEST = 'FETCH_STUDENTDETAIL_REQUEST'
export const FETCH_STUDENTDETAIL_SUCCESS = 'FETCH_STUDENTDETAIL_SUCCESS'
export const FETCH_STUDENTDETAIL_FALIURE = 'FETCH_STUDENTDETAIL_FALIURE'
